function generate_plots(case_type, case_value, time_V, beta, p, r, phi, psi, t_beta, t_p, t_r, t_phi, t_psi, legends)
    input_case = sprintf('$\delta_a = %d^\circ, \delta_r = 0^\circ$', case_value);
    title_str = sprintf('Response of System @ %s', input_case);
    
    % Plot Beta
    myplot_general({beta.sim(:, case_value), rad2deg(beta.linear(:, case_value)), rad2deg(beta.dr(:, case_value)), rad2deg(beta.dof2(:, case_value))}, ...
                   {time_V, t_beta.linear(:, case_value), t_beta.dr(:, case_value), t_beta.dof2(:, case_value)}, ...
                   x_label, y_labels{1}, title_str, legends.beta);
    
    % Plot p
    myplot_general({p.sim(:, case_value), rad2deg(p.linear(:, case_value)), rad2deg(p.dr(:, case_value)), rad2deg(p.roll(:, case_value))}, ...
                   {time_V, t_p.linear(:, case_value), t_p.dr(:, case_value), t_p.roll(:, case_value)}, ...
                   x_label, y_labels{4}, title_str, legends.p);
    
    % Plot r
    myplot_general({r.sim(:, case_value), rad2deg(r.linear(:, case_value)), rad2deg(r.dr(:, case_value)), rad2deg(r.dof2(:, case_value))}, ...
                   {time_V, t_r.linear(:, case_value), t_r.dr(:, case_value), t_r.dof2(:, case_value)}, ...
                   x_label, y_labels{5}, title_str, legends.r_dr);
    
    % Plot phi
    myplot_general({phi.sim(:, case_value), rad2deg(phi.linear(:, case_value))}, ...
                   {time_V, t_phi.linear(:, case_value)}, ...
                   x_label, y_labels{2}, title_str, legends.phi);
    
    % Plot psi
    myplot_general({psi.sim(:, case_value), rad2deg(psi.linear(:, case_value))}, ...
                   {time_V, t_psi.linear(:, case_value)}, ...
                   x_label, y_labels{3}, title_str, legends.psi);
end